### ISSUE TITLE
SICF services

### ISSUE THREAD

**Issue by larshp** [techaware/wdalv_config#1]
Hi Rahul,
Can you try adding the SICF services for the web dynpro applications to the repository? Object type = SICF should appear in ZABAPGIT for the repository. Then the applications should be possible to start right after installing via abapGit.

Also for your information I've added issue https://github.com/larshp/abapGit/issues/121 for abapGit

**Comment by larshp** [comment]
Hi,
Can you try updating abapGit and commiting the files again? this should solve some diffs in TABL + sorting for WDYN

It looks like there is an issue in abapGit regarding
ACCESSIBILITY_DESCR
will look into this after you've updated the files

**Comment by techaware** [comment]
Unable to add SICF node to ABAPGIT repo. Details at https://github.com/larshp/abapGit/issues/121

**Comment by larshp** [comment]
update to latest abapGit version and try again

**Comment by techaware** [comment]
Thanks. Will get back once done. Happy new Year!

On Mon, Dec 28, 2015 at 9:34 AM, Lars Hvam notifications@github.com wrote:

> update to latest abapGit version and try again
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/techaware/wdalv_config/issues/1#issuecomment-167608603
> .

## 

Rahul Aware

**Comment by techaware** [comment]
After updating the latest ABAPGIT - I was able to add SICF nodes to the GIT repo.
